---
- wait_for_connection:
    timeout: 10
  register: ssh_conn
  ignore_errors: yes
- debug: var=inventory_hostname


- name: get hostname
  shell: hostname
  register: remove_yml_output
- debug: var=remove_yml_output

