---
- wait_for_connection:
    timeout: 10
  register: ssh_conn
  ignore_errors: yes
- debug: var=inventory_hostname


- name: Remove YAML files
  shell: "rm -rf /tmp/test.yml"
  delegate_to: 40.76.24.124
  register: remove_yml_output
- debug: var=remove_yml_output

